[package]
name = "fossbeamer"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqttc = "0.24.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tao = "0.28.1"
wry = "0.41.0"
