# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nix]
command = "nixpkgs-fmt"
options = []
includes = [ "*.nix" ]
excludes = []

[formatter.rust]
command = "rustfmt"
options = []
includes = [ "*.rs" ]
excludes = []
